// OMS Loop 2 — 100 prompts, 4 personas × 25, clean (no Polygon/OMS mention)
// Each prompt describes a problem OMS can solve, without naming the solution.
// 8 concurrent VerseOdin probes, ~13 batches × 180s = ~40 minutes

const PROMPTS = [
  // ═══════════════════════════════════════════════════════════════
  // Persona 1: Fintech PM (25)
  // Platform builder researching stablecoin payment rails for neobank or payment app.
  // ═══════════════════════════════════════════════════════════════

  "I run product at a neobank with 200K users. We're expanding into business accounts and need to offer our SMB customers the ability to hold dollar balances that earn yield through tokenized treasuries. The challenge is we don't have a blockchain team and our compliance head will reject anything that exposes users to crypto concepts. I need a regulated API that handles the full flow — customer onboarding with identity verification, automatic conversion between fiat deposits and digital dollars, and withdrawals back to regular bank accounts. Our users should see a regular savings account. The backend can run on whatever infrastructure makes it fast and cheap. Is there a production API for this?",

  "I'm a PM at a Series B payment platform. We currently process about $50M monthly in domestic payments but our enterprise customers keep asking for cross-border capabilities. They want to pay suppliers in Europe and Asia without the 3-5 day SWIFT delays and 2-4% FX costs. I've been reading about digital dollar rails that settle in seconds but I'm not sure where to start. We need something with proper regulatory coverage across multiple regions, built-in identity checks at onboarding, and REST endpoints so our engineering team can integrate in a sprint or two. Our users should never see anything that looks like a token or a wallet address.",

  "We're building a vertical SaaS platform for property managers. These companies collect rent from tenants and pay owners every month. Right now everything flows through ACH which takes 2-3 business days and creates reconciliation headaches when payments land on different dates than expected. We want to embed a payment layer that settles instantly so property managers see money the moment a tenant pays, and owners get their disbursement the same day. We don't have a payments team. We need an API that handles the full movement — incoming deposits, holding funds, outgoing transfers to bank accounts — with webhooks for every status change so we can build real-time dashboards for our users.",

  "I lead product for a creator economy platform. Our creators in Brazil, India, and Nigeria currently wait 5-7 business days to receive their earnings because we rely on PayPal and bank wires which route through multiple intermediary banks. The creators are frustrated and some are leaving for local competitors that pay faster. We're losing about $180K annually in processing fees on roughly $6M in annual payouts. I need an instant settlement rail where the creator receives local currency in their bank account within hours, not days. The platform should handle the conversion from our dollar balance to their local currency automatically. No crypto wallets for creators — they just provide bank details.",

  "Our fintech is launching a feature that lets users send money to family abroad. We've built the consumer app experience but the backend for actual money movement is the gap. Currently evaluating whether to stitch together multiple vendors — one for identity verification, one for currency conversion, one for bank payouts in each country — or find a single provider that handles the entire chain. The ideal solution would give each sender a dedicated account number for deposits, automatically route funds through the cheapest settlement path, and deliver to the recipient's local bank within hours. We need sandbox access to test the full flow before going live. What options handle this end-to-end?",

  // 20 more fintech PM prompts...
  "We're a neobank targeting freelancers and solopreneurs. These users receive payments from multiple clients in different currencies and then spend or save that money. Their biggest complaint is the 1-3% they lose on every currency conversion. I'm evaluating whether there's infrastructure that can hold multiple currency balances and convert between them at near-zero cost using digital dollar rails. The UX should be invisible — users see their balance in their preferred currency, spend with a card, and never interact with any blockchain concepts. I need a partner that handles the treasury management, currency conversion, and compliance on the backend.",

  "I manage a bill-splitting app with 2M users. We're adding a feature where groups can pool money for shared expenses — rent, utilities, dinner tabs. Right now each member pays via card or ACH and we batch-settle to the person who paid. It takes 2-3 days for money to actually arrive. We want to move to a model where every payment settles the moment the user confirms, and the recipient can withdraw to their bank account immediately. I need an API that creates virtual balances per group, processes incoming payments from multiple sources, and handles outgoing transfers to individual bank accounts. No crypto UX for our users. They just see 'you've been paid.'",

  "We run a subscription billing platform for SaaS companies. Our customers collect payments via card and ACH, then need to reconcile deposits, handle refunds, and manage cash flow. The settlement delays from ACH batch processing create constant support tickets — 'did my customer pay yet?' We want to offer our SaaS customers a settlement option that finalizes in seconds rather than days. I'm looking for infrastructure where incoming ACH deposits can be accelerated through a secondary rail that settles continuously, not in nightly batches. The SaaS company should just see 'payment received' and the funds should be available for their own disbursements immediately.",

  "I'm the CTO of an embedded finance startup. We help non-fintech companies add financial products to their apps. One of our clients, a logistics platform, needs to hold driver earnings and pay out daily. Another client, a healthcare platform, needs to collect patient payments and settle to providers weekly. Each use case has different settlement cadences and rail requirements. I'm looking for a programmable money movement API where we define the flow for each client — collect here, hold for X days, disburse there — without building per-use-case infrastructure. It needs to be API-first with strong webhook coverage and a sandbox where we can model different flows before deploying to production.",

  "We're a Series A fintech building a neobank for immigrants. Our users send money home regularly — these remittances are often $200-500 at a time, sent monthly. The traditional remittance corridors eat 5-7% in fees and take 2-5 days. We want to bring that down to near-zero cost and same-day delivery by using digital settlement rails. But our users are not technical — they should see a regular banking app where they enter an amount, pick a recipient, and hit send. The backend needs to handle the identity checks, the conversion, the settlement, and the delivery to the recipient's local bank or mobile wallet. We need coverage across at least the top 15 remittance corridors from the US.",

  "I head product for a digital bank focused on small businesses. Our customers need to pay suppliers, contractors, and vendors — often internationally. A typical use case: a small manufacturer in Ohio needs to pay a parts supplier in Mexico. Today they use wire transfers that cost $25-45 each and take 3-5 days. We want to build an international payment feature that gives them same-day delivery at a predictable low fee. I need a partner that can connect our banking app to settlement rails that work across both US and Mexican banking systems, handle the currency conversion at transparent rates, and provide a clear transaction trail our compliance team can audit.",

  "We operate a neobank in Southeast Asia and we're expanding to serve freelancers who work for US and European clients. These freelancers currently receive payments through PayPal and Wise, losing 3-5% in fees before the money even reaches their local account. We want to integrate rails where the US/European client pays in their local currency, the funds settle through a digital dollar intermediary (which is faster and cheaper than correspondent banking), and the freelancer receives their local currency — Indonesian rupiah, Philippine peso, Vietnamese dong — in their bank account within hours. The conversion from dollar to local currency should happen automatically. We need regulation-compliant infrastructure with KYC at onboarding.",

  "I'm building a payroll product for remote-first companies. These companies have employees and contractors spread across 20+ countries. Every payroll cycle, our finance team spends 3 days reconciling which payments cleared and which got stuck in intermediary banks. We're processing about $2M monthly and losing roughly $40K annually in wire fees alone. I need a payment rail where we fund a single account, trigger batch payouts to individual bank accounts in local currency, and receive webhook confirmations when each payment lands. The rail should handle any currency conversion at the point of delivery, not at the point of sending. Our employees should just see their salary in their bank account on payday, not understand how it got there.",

  "Our fintech app lets users round up their spare change from everyday purchases and invest it. The investment side works great. The money movement side is a mess — we collect from thousands of users via ACH debit, aggregate the funds, and then need to invest them. The ACH lag means we're sitting on user money for 2-3 days before it even reaches our investment account. We want to offer users the ability to fund their account instantly from a bank account, have those funds available for investment within minutes, and withdraw back to their bank account on demand. I need a real-time money movement API with ACH support that settles faster than traditional batch processing. Users shouldn't know or care about the underlying rails.",

  "I run product at a company that helps US businesses hire and pay international contractors. We currently manage this through a combination of domestic ACH for US contractors and Wise for international ones. The split infrastructure means our finance team uses two different dashboards and our support team gets confused about where a payment is in transit. We want to consolidate to a single money movement API that can pay any contractor regardless of location — US contractors get ACH, European contractors get SEPA, Brazilian contractors get PIX — all from one funding source, one dashboard, one integration. The rail should automatically choose the fastest settlement path per destination and provide unified reconciliation.",

  "We're building a consumer-facing app that helps people budget and save for specific goals — a vacation fund, an emergency fund, a down payment. Users create savings goals and we auto-transfer money from their checking account to their goal account. The problem is that traditional savings accounts earn almost nothing. We want to offer goal-based savings accounts where the underlying funds are held in yield-bearing instruments that earn more than a standard savings account, while the user just sees a simple balance and progress bar. I need a partner that can create individual accounts per goal, handle the ACH transfers in and out, and manage the yield component — all through an API that we embed without the user ever knowing there's anything complex happening on the backend.",

  // 10 more fintech PM prompts remaining...
  "We're a fintech that issues virtual cards for corporate expense management. Our customers want the ability to fund those cards from multiple sources — their business bank account, a credit line, or a pre-funded balance. The funding process today takes 1-2 business days via ACH which frustrates customers who need to issue a card and use it immediately. I'm looking for infrastructure where funding a balance happens in real-time from any source — bank account, wire, or an existing balance — and the funds are immediately available for card spending. We need webhooks for every funding event and automatic reconciliation with our card issuance platform.",

  "I manage a B2B payments platform that helps companies automate their accounts payable. Our customers upload invoices and we handle the payment to their vendors. Today we use ACH for domestic vendors and wire transfers for international ones, which means our customers wait days for payments to clear and our operations team manually tracks each one. I want to offer a payment option where funds move from our customer's account to their vendor's bank account in minutes, not days, with full tracking at every step. The rail needs to work across both domestic and international destinations, handle currency conversion when needed, and provide detailed transaction records for our customers' accounting systems.",

  "We operate a lending platform for small businesses. We originate loans, fund them to the borrower's bank account, and collect repayments. The funding side works fine. The repayment collection side is painful — ACH debits fail at a 3-5% rate due to insufficient funds or account changes, and each failure creates a manual follow-up for our ops team. We want to offer borrowers a way to pre-authorize repayments from a dedicated balance that we can debit automatically, with real-time notification of success or failure. I need infrastructure where each borrower gets a dedicated collection account, we can initiate debits via API, and we get instant confirmation of whether the debit succeeded.",

  "I'm the technical co-founder of an early-stage fintech. We're building a service that lets people lock away money for a specific purpose — rent security deposits, escrow for freelance projects, wedding vendor payments. The money needs to be held securely, earn a small return while locked, and be releasable to the recipient when conditions are met. We don't want to become a bank or a trust company. We need a partner that can create segregated balances per transaction, hold the funds in a compliant custody structure, and release them via ACH or instant transfer when our smart contract or business logic determines the conditions are met. The partner handles the regulatory piece. We handle the user experience and the conditions logic.",

  "Our fintech offers a debit card tied to a spending account. We want to let users earn rewards on their balance — similar to how a high-yield savings account works — without the user having to move money between accounts. The current model requires us to sweep funds nightly to a partner bank's savings product, which adds operational complexity and delays reward crediting. I need a balance infrastructure where funds automatically earn yield while remaining available for card spending. When the user swipes their card, the exact amount is debited from the yielding balance in real-time. The yield should be transparent and creditable daily. The user just sees their balance and reward earnings — no separate savings account, no sweep delays.",

  // 5 more fintech PM prompts...
  "We run an invoice factoring platform. Small businesses sell their unpaid invoices to us at a discount and we advance them cash. The advance typically takes 1-2 business days via ACH which is too slow for business owners who are often covering payroll or urgent supplier payments. We want to offer same-day advances where the business gets funds in their bank account within hours of selling an invoice. I need a money movement partner that can push funds to any US bank account with settlement in minutes, not days, and provide confirmation when the funds land. The rail should cost significantly less than wire transfers so we can offer competitive advance rates to our customers.",

  "I lead engineering for a consumer savings app that uses behavioral psychology to help people save more. Our core mechanic is automated savings rules — 'save $5 every time I go to the gym' or 'round up every purchase to the next dollar.' These micro-deposits happen frequently and need to post immediately for the behavioral feedback loop to work. ACH batch processing means users wait 2-3 days to see their savings. I need a settlement partner that can accept frequent small-value deposits in real-time and credit them to a user's balance instantly. The rail needs to handle high transaction volumes at low per-transaction cost, since our average deposit is under $10.",

  "We're a fintech that helps people build credit through secured loans. The model works like this: the user deposits money into a locked savings account, we issue them a loan equal to their deposit, they repay the loan over 12 months, and at the end they get their deposit back. The challenge is that holding thousands of individual deposits requires a trust or escrow structure that's expensive to set up and maintain. I need a partner that can create individual segregated accounts for each user, hold the funds in a compliant structure, earn a return on the pooled deposits to help cover our operational costs, and release the funds back to the user via ACH when the loan is repaid.",

  // total: 25 fintech_pm

  // ═══════════════════════════════════════════════════════════════
  // Persona 2: Marketplace CTO (25)
  // Running a two-sided marketplace, bleeding on cross-border seller payouts.
  // ═══════════════════════════════════════════════════════════════

  "I'm the CTO of an online marketplace with 8,000 active sellers across 35 countries. Our sellers range from individual artisans in Morocco to small manufacturers in Vietnam. Every month we process about $4M in seller payouts through a mix of PayPal, Wise, and direct bank wires. Our finance team tells me we're spending roughly $120K annually on fees — wire transfer charges, PayPal's cross-border markup, and hidden FX spreads. The bigger problem is speed: sellers in emerging markets sometimes wait 7 days to see money in their bank account. During that week, they're emailing our support team asking where their payment is. We get about 400 'where's my money' tickets per payout cycle. I need a single global payout API that can send money to any seller, in any country, in their local currency, within 24 hours — ideally same-day. The sellers shouldn't need anything more than their bank account number. No app downloads, no crypto wallets, no additional signups. Is there a platform that handles this at scale?",

  "We run a freelance marketplace connecting developers in Latin America and Africa with clients in the US and Europe. Our freelancers currently receive payments through PayPal, which charges them 4-5% in fees when you include the currency conversion spread. A freelancer who earns $2,000 a month is losing $80-100 just to payment processing. These are meaningful amounts in their local economies. We want to shift to a model where the freelancer provides their local bank details once, and every payment from a client settles to their bank account in their local currency — Brazilian reais, Nigerian naira, Kenyan shillings — within hours of the client approving the work. The platform should handle the conversion from the client's currency to the freelancer's local currency at a transparent rate that's significantly better than PayPal's. We need API documentation our small engineering team can integrate in a week.",

  "I run engineering for a creator platform where fans subscribe to creators for exclusive content. We have 15,000 active creators and payout about $2.5M monthly. Today we use Stripe Connect for domestic creators and manual PayPal payouts for international ones. The dual system means our finance team spends the first week of every month running payouts — checking exchange rates, initiating transfers, reconciling what cleared vs what didn't. Creators in international markets get paid 3-5 days after their US counterparts. We want a single payout API where we specify the creator's bank details and the amount in their local currency, and the platform handles everything else — the conversion, the settlement, the delivery. We need webhook events for every stage so our creator dashboard updates in real-time when money is on the way. Creators who stream live and see donations in real-time expect their earnings to be available quickly.",

  "We operate a B2B wholesale marketplace connecting manufacturers in China and India with retailers in North America. The transactions are larger — average order value around $15,000 — and currently settle through traditional trade finance channels which involve letters of credit, wire transfers, and multiple intermediary banks. Each transaction costs $50-150 in banking fees and takes 5-10 business days to fully settle. We want to modernize this with a digital settlement rail that can handle large-value B2B transactions at lower cost and faster speed. The manufacturer should receive confirmation that funds are secured when the order is placed, and final settlement should happen within 24 hours of order fulfillment. We need a platform that can hold funds in escrow during the fulfillment period and release them to the manufacturer upon delivery confirmation. Compliance and audit trail are non-negotiable for our enterprise buyers.",

  "I'm the head of payments for a gig economy platform that connects dog walkers, house cleaners, and handymen with customers. Our workers complete 50,000+ gigs per week and expect to get paid quickly — many of them live paycheck to gig. Currently we batch-process payouts twice a week via ACH, which means a walker who worked Monday morning might not see the money until Thursday. We're losing workers to competitors that offer daily payouts. I need a payout infrastructure that can process thousands of individual payments daily, each going to a worker's bank account, with settlement in hours not days. The workers should be able to choose their payout cadence — daily, weekly, on-demand — and the rail should handle the load without manual intervention from our team. Cost per payout needs to be under $0.25 to be viable for our unit economics.",

  // 20 more marketplace CTO prompts...
  "We run a print-on-demand marketplace where independent artists upload designs and we handle production and shipping. When a customer buys a t-shirt with an artist's design, we need to pay the artist their royalty — typically $3-8 per sale. With 100,000+ sales monthly, we're making a massive number of small payouts. The current process batches artist royalties monthly and pays via PayPal or ACH, which means artists wait 30-45 days to see their earnings. We want to move to a model where artists can withdraw their balance on-demand to their bank account and receive funds within 24 hours. The payout rail needs to handle micro-payouts at near-zero cost — paying $0.25 to send $3 doesn't work economically.",

  "I lead technology for a vacation rental marketplace. Hosts list their properties and guests book and pay. The payment flow is: guest pays at booking → we hold the funds → host receives payout after check-in. Currently funds sit in our Stripe account for weeks between booking and payout, and hosts receive their money 1-2 days after check-in via ACH. We want hosts to receive their payout on the same day as check-in, and ideally we want the held funds to earn a return during the interim period. I need a treasury and payout solution where guest payments land in an interest-bearing account, funds are available for instant payout on the check-in date, and hosts receive money in their bank account same-day. The platform should handle the compliance of holding customer funds and provide full visibility into where every dollar is at every moment.",

  "We're a food delivery marketplace operating in 8 countries across Asia. Our delivery riders complete about 200,000 orders daily and expect to be paid within 24 hours. Currently we pay riders weekly via bank transfer, which causes constant friction — riders need daily cash flow for fuel and vehicle maintenance. We want to offer daily payouts to riders' bank accounts or mobile wallets. The challenge is the volume: 200,000 micro-payouts daily, each $5-30, across 8 different banking systems and mobile money providers. We need a payout API that can batch-process this volume, handle the routing to different payment rails per country (bank transfer in Thailand, GCash in Philippines, GoPay in Indonesia), and provide reconciliation data we can feed into our rider app so they see their earnings in real-time.",

  "I'm the CTO of a secondhand luxury goods marketplace. Sellers ship items to our authentication center, we verify them, then sell to buyers. Sellers get paid after authentication and sale — a process that currently takes 7-10 business days from when they ship the item. This delay is the #1 seller complaint. We want to offer sellers the option of instant payout as soon as their item passes authentication, rather than waiting for the buyer payment to fully settle through traditional rails. I need a platform that can advance funds to sellers against authenticated inventory, settle to their bank account in hours, and recoup the advance when the buyer payment clears. This requires a partner that understands the collateral value of authenticated goods and can underwrite the advance risk.",

  "We operate a tutoring marketplace connecting students with tutors globally. A student in London pays for a session with a tutor in South Africa. The student pays in GBP via card, and the tutor needs to receive ZAR in their South African bank account. Currently we route this through a combination of Stripe for collection and Wise for payout — two separate systems, two sets of fees, two reconciliation processes. We want a single platform where the entire flow is handled: student pays → funds convert to a stable intermediary → tutor receives local currency in their bank account. The platform should handle the GBP→ZAR conversion at the time of payout to give the tutor the best rate, not at the time of collection. We process about 15,000 sessions monthly and the dual-system overhead is becoming unsustainable as we scale.",

  // 15 more marketplace CTO prompts...
  "We run a crowdfunding platform for creative projects. Backers pledge money to projects, and if the project reaches its funding goal, the creator receives the funds. If not, backers get refunded. The current process uses Stripe to hold pledges and ACH to disburse to creators, which means creators wait 5-7 business days after a successful campaign to receive funds. During that window, they can't start production. We want to offer creators the ability to receive funds within 24 hours of a successful campaign. Additionally, we want to hold backer pledges in an account that earns a return during the campaign period (typically 30-60 days), which could help fund our platform fees. I need a treasury partner that can hold pledged funds, earn yield, and disburse to creators' bank accounts rapidly when campaigns succeed.",

  "I head engineering for a ticket resale marketplace. Fans buy and sell tickets to events — concerts, sports, theater. When a seller lists a ticket and it sells, the seller needs to get paid, but the payout should only happen after the event date to protect against fraud (if the ticket is invalid, we need to refund the buyer). Currently we hold seller funds in escrow until the event, then batch-pay via ACH. Sellers complain about the wait. We want to offer sellers the option to receive their funds immediately after the ticket sells, with the understanding that if a dispute arises, the funds can be recovered from their linked bank account. I need a payout partner that can push funds to seller bank accounts in real-time and support clawback capabilities for disputed transactions. The partner needs to handle ACH returns and provide clear dispute resolution workflows.",

  "We're a peer-to-peer car rental marketplace. Car owners list their vehicles, renters book them, and owners get paid after the rental period ends. The current payout process takes 2-3 business days after the rental completes, which frustrates owners who treat this as a side income stream. We want to pay owners the moment the renter returns the car and the owner confirms no damage. I need a payment rail where we can hold the renter's payment, verify the rental is complete, and release funds to the owner's bank account within minutes — not days. The rail should work for both domestic and international owners, handle currency conversion when the renter paid in a different currency, and provide clear transaction records for our customer support team to reference when owners ask about payment status.",

  "I manage platform operations for a digital products marketplace — stock photos, website templates, music samples. Creators upload their work and earn royalties when customers download. The average royalty is $2-8 per download, and our top creators have thousands of downloads monthly. Currently we batch-pay creator royalties monthly via PayPal. Creators hate the monthly cycle and the PayPal fees. We want to offer creators a real-time earnings dashboard where they can withdraw their balance to their bank account anytime, with the funds arriving same-day. We have 25,000+ active creators and need an API that can handle on-demand micro-payouts at scale without our finance team manually processing each withdrawal request.",

  "We operate a language tutoring marketplace. Students book sessions with native-speaking tutors. The payment model is per-minute — a 30-minute session costs $15-25 depending on the tutor's rate and language. Tutors are mostly in Latin America, Africa, and Southeast Asia. Currently we pay tutors monthly via Wise, which means a tutor who taught 50 sessions in a month waits 30+ days to see the money, then loses another 2-4% in Wise fees. We need to move to a model where tutors can withdraw earnings on-demand to their local bank or mobile money account, receive funds within hours, and pay a fraction of the current fee structure. The challenge is serving tutors across 40+ countries with different banking systems and keeping per-transaction costs low enough that a $15 per-session tutor isn't losing a significant percentage to payment fees.",

  // more marketplace CTO...
  "I run product for an equipment rental marketplace — think cameras, drones, audio gear. Owners list their equipment and renters book by the day. The payment flow involves a security deposit that gets held and released, plus the rental fee that goes to the owner. Currently we use Stripe for the whole flow but security deposit holds on cards are limited to 7 days and many rentals are longer. We need a payment system that can hold variable amounts for variable durations, release holds instantly when equipment is returned undamaged, and pay the owner their rental fee minus our commission — all within one API. The hold/release cycle needs to be fully programmable so we can automate the dispute resolution process when equipment is returned damaged.",

  "We're a wholesale marketplace for restaurant supplies. Restaurants order from multiple suppliers in a single transaction, and we split the payment to each supplier. Average transaction is $2,000-5,000 with 3-5 suppliers per order. Today the customer pays us via ACH (2-3 day settlement), then we batch-pay suppliers via ACH (another 2-3 days). Suppliers are waiting nearly a week to get paid from the moment the restaurant places the order. We want to accelerate this: the restaurant pays, the funds settle to us within hours, and we push payments to each supplier's bank account the same day. We need a platform that handles the split-payment logic, routes each portion to the correct supplier account, and provides per-supplier reconciliation.",

  "I manage engineering for a consulting marketplace where companies hire experts for short-term projects. The typical engagement is $5,000-25,000 over 2-8 weeks. Companies pay upfront into escrow, and experts draw down as they complete milestones. Currently the escrow is managed by a third-party trust provider that charges 1-2% and takes 3-5 days to process milestone releases. We want to bring escrow in-house with a digital settlement partner that can hold funds, track milestone completion, and release payments to expert bank accounts within hours of milestone approval. The partner needs to operate in a regulated custody framework since we're holding client funds, and provide the compliance documentation our enterprise clients require.",

  "We run a small marketplace that connects local farmers with restaurants. Restaurants order produce and pay upon delivery confirmation. Farmers need to get paid quickly — they have thin margins and depend on cash flow to cover seeds, labor, and equipment. Currently we process payments via ACH, which means a farmer who delivers on Monday gets paid on Thursday. We want to offer farmers same-day settlement. The average transaction is $200-800. I need a payout partner that can push funds to any US bank account within hours of delivery confirmation, at a cost that works for sub-$1,000 transactions. The rail should provide real-time status so our app shows the farmer 'payment sent' the moment the restaurant confirms delivery.",

  // total: 25 marketplace_cto

  // ═══════════════════════════════════════════════════════════════
  // Persona 3: Remittance Founder (25)  
  // Consumer cross-border transfers. US→LatAm, US→Africa, US→Asia.
  // ═══════════════════════════════════════════════════════════════

  "I founded a remittance startup focused on the US-to-Mexico corridor. Our customers are mostly first-generation immigrants sending $200-400 home every month to support family. Today they use Western Union or MoneyGram and pay 5-7% in fees — on a $300 transfer, that's $15-21 just to send money. The money typically arrives in 1-2 days if sent to a bank account, or within hours if picked up as cash. We want to bring the cost under 1% and offer instant delivery to both bank accounts and cash pickup locations. I need a platform partner that can accept deposits from senders (via ACH, debit card, or cash at retail), convert to a digital dollar for the transfer leg (where it moves cheap and fast), and deliver to recipients in Mexican pesos — either to their bank account via SPEI or as cash at OXXO and other retail pickup points. The partner needs to handle the regulatory compliance for both the sending side in the US and the receiving side in Mexico.",

  "I'm building a remittance app targeting the Nigeria corridor. Nigeria is one of the largest remittance markets globally, with the diaspora sending billions home annually. Today's rails are expensive — Western Union and MoneyGram charge 3-5%, and bank wires get eaten by correspondent banking fees. Additionally, Nigeria has a parallel exchange rate issue where the official rate and the market rate diverge significantly, meaning recipients often get less value than they should. We want to build a product where US senders fund transfers in dollars, the value moves through a digital dollar rail at near-zero cost, and recipients receive naira in their bank account or mobile wallet at the best available rate. The partner needs to have a licensed on-the-ground presence in Nigeria that can handle the last-mile delivery to local banks and mobile money providers like Paga and OPay. They also need to manage the compliance — KYC for senders, AML screening, and Nigerian regulatory requirements.",

  "We run a digital remittance service for Indian expats. India is the largest remittance receiving country in the world, with $100B+ flowing in annually. Our customers send money home for family support, education, medical expenses, and property purchases. The amounts vary from $200 for monthly family support to $10,000+ for education fees or property down payments. We currently use traditional correspondent banking which takes 2-3 business days and costs 1-3% depending on the corridor partner. We want to shift to a digital settlement rail where the transfer leg settles in minutes and the cost drops to a flat fee under $2 regardless of amount. The recipient should receive rupees in their bank account via UPI or IMPS — India's real-time payment systems. The partner needs to integrate with India's banking infrastructure, handle the rupee conversion at a competitive rate, and provide transaction tracking our customers can follow in real-time.",

  "I'm building a remittance product for the Philippines market, where over 10 million overseas Filipino workers send money home. The country has a well-developed mobile money infrastructure — GCash and PayMaya have tens of millions of users — and recipients increasingly prefer digital delivery over cash pickup. Our product would let US-based senders fund transfers from their bank account or card, have the funds settle through a digital intermediary, and land in the recipient's GCash, PayMaya, or bank account within minutes. We need a partner that has direct connections to Philippine mobile money providers and banks, can handle the USD to PHP conversion at a competitive rate, and provides API endpoints for every step — sender registration with KYC, funding source verification, transfer initiation, and delivery confirmation. The partner should also support cash pickup at remittance centers for recipients who prefer that option.",

  "We're building a cross-border payment app for the US-to-Guatemala corridor, but with a twist: we want to serve rural areas where bank penetration is low but mobile phone adoption is high. Our recipients typically receive cash at local agent locations because they don't have bank accounts. The current remittance options are expensive and the agent network is concentrated in urban areas. We want to build a service where senders fund digitally, the transfer settles cheaply, and recipients can pick up cash at a wider network of rural retail locations — corner stores, pharmacies, mobile money agents. I need a rails partner that has a cash disbursement network with coverage in rural Guatemala, can generate unique pickup codes for each transaction, and confirms delivery via API when the cash is collected. The partner should also support bank account delivery for recipients who do have accounts, so we can offer both options.",

  // 20 more remittance...
  "I started a company focused on US-to-Kenya remittances. Kenya has M-Pesa — the most successful mobile money platform in the world — and most recipients prefer to receive money in their M-Pesa wallet rather than a bank account. The current remittance process involves multiple hops: sender pays in USD, a correspondent bank converts to KES, an intermediary routes to Safaricom, and M-Pesa credits the recipient. Each hop adds cost and delay. We want to collapse this into a direct flow where we collect from the sender, route through a digital dollar intermediary for the cross-border leg, and deliver directly to the recipient's M-Pesa wallet — with no correspondent banks taking a cut. I need a partner that has a direct connection to Safaricom's M-Pesa API or a licensed aggregator, can handle the KES conversion at the point of delivery, and can process thousands of transfers daily during peak times like holidays and school fee payment seasons.",

  "We're building a remittance platform for the US-to-Vietnam corridor. Vietnam has a young, tech-savvy population and high smartphone penetration. Most remittances currently flow through traditional money transfer operators or informal hawala networks. We want to create a formal, digital-first alternative that's cheaper and faster. Senders would link their US bank account or debit card, the funds would settle through a digital dollar rail, and recipients would receive Vietnamese dong in their bank account or MoMo/ZaloPay mobile wallet. The partner needs to have Vietnamese banking licenses, integration with local payment rails, and the ability to handle the dong conversion at competitive rates. Compliance is important — Vietnam has strict foreign exchange controls and all cross-border transfers need to be reported to the State Bank of Vietnam.",

  "I run a remittance company serving the Ethiopian and Somali diaspora in the US. These corridors are challenging because of limited banking infrastructure in the receiving countries and complex regulatory environments. Recipients often receive cash through local agents rather than bank accounts. The current process relies on hawala networks that are informal, unregulated, and vulnerable to disruption. We want to build a transparent, regulated alternative where every transfer has a clear audit trail and the sender knows exactly what the recipient will receive. I need a partner that has licensed operations in East Africa, can deliver to local banks where available and to agent networks for cash pickup where not, and provides the compliance documentation required by US regulators for serving these corridors. The partner should be able to handle the birr and shilling conversions at transparent rates.",

  "We're a remittance startup focused on speed — our value proposition is 'money home in 30 minutes or it's free.' We serve the US-to-Colombia corridor where the traditional options take 1-2 business days for bank delivery and cost 3-5%. We want to offer bank delivery via Colombia's PSE system and cash pickup via Efecty and Baloto networks. The operational challenge is that we need a partner who can guarantee sub-30-minute delivery windows, which means the settlement needs to happen in seconds rather than hours, and the local payout rails need to be always-on. I need a rails provider that can process the full flow — sender funding verification, digital dollar transfer, COP conversion, and local delivery — with SLAs for each step. Webhook confirmations at each stage are essential so we can show the sender a real-time progress bar in our app.",

  "I'm building a multi-corridor remittance platform starting with US-to-Bangladesh, US-to-Pakistan, and US-to-Nepal. These three corridors share similar dynamics: large diaspora populations, heavy reliance on remittances for family support (10-30% of household income in some regions), and limited digital infrastructure in the receiving countries. Most transfers today go through money transfer operators that charge 3-5% and take 1-3 days. We want to build a digital-first alternative. The challenge is that each corridor has different receiving infrastructure — Bangladesh has bKash mobile money, Pakistan has JazzCash and EasyPaisa, Nepal has limited digital options and most recipients need cash. We need a platform that can handle all three corridors through a single API, adapting the delivery method to what's available in each receiving country — mobile wallet in Bangladesh, bank transfer or mobile wallet in Pakistan, cash pickup in Nepal. The partner should abstract this complexity so our app just specifies the recipient, amount, and delivery preference.",

  // 15 more remittance...
  "We operate a remittance service for the US-to-Dominican Republic corridor. Our users send money home for family support — groceries, school fees, medical bills, home repairs. The average transfer is $150-250. Currently these go through money transfer operators at 4-6% fees. We want to offer transfers at 1% or less. The Dominican Republic has a growing network of agent locations (banks, remittance centers, supermarkets) where recipients can pick up cash. We need a partner that has a Dominican peso payout network with good coverage, can deliver to bank accounts for the growing share of recipients who have them, and provides real-time delivery confirmation. The partner should handle the compliance — both US-side KYC/AML for senders and Dominican-side regulatory requirements for money service businesses receiving foreign transfers.",

  "I founded a startup building a 'remittance as a benefit' product for US employers. Companies with large immigrant workforces — hospitality, agriculture, construction, healthcare — offer remittance as an employee benefit, similar to how they offer health insurance or 401k. The employer deducts a portion of the employee's paycheck and sends it to their family abroad, often at a subsidized or zero-fee rate. We need a white-label money movement partner that can accept batch funding from employers (via ACH or wire), route individual transfers to each employee's designated recipient in their home country, and deliver in local currency. The partner needs to handle the per-recipient compliance — each employee's family member needs KYC verification in their home country. The partner should also provide a dashboard where employers can see aggregate transfer volumes and employees can track individual transfers.",

  "We're building a remittance app specifically for the US-to-Cuba corridor, which has unique regulatory constraints due to US sanctions and Cuban currency complexity. Transfers need to comply with OFAC regulations, and the receiving infrastructure is limited — most recipients pick up cash at government-operated remittance centers. We want to create a compliant, transparent service where US senders can fund transfers digitally and recipients pick up cash at designated locations in Cuba. The partner needs to have OFAC-compliant operations, a physical presence or licensed partner in Cuba, and the ability to handle the Cuban peso conversion. Transaction limits and reporting requirements are strict — the partner should build these into the API so we don't accidentally process a non-compliant transfer.",

  "I run a remittance startup focusing on the US-to-Honduras corridor, with a focus on serving rural communities where many recipients live in areas without bank branches. The current options are expensive money transfer operators or informal couriers. We want to build a network of local agents — small businesses, pharmacies, community centers — that can serve as cash pickup points in rural areas. We need a platform partner that provides the digital rails for the transfer (sender funding, cross-border settlement, currency conversion) while we build the local agent network. The partner should generate unique transaction codes that recipients present at agent locations, confirm delivery via API when the code is redeemed, and handle the settlement to our agent partners for the cash they dispense.",

  "We're a fintech building a multi-currency digital wallet for immigrants in the US. The wallet lets users hold balances in both USD and their home currency, spend with a card in the US, and send money home to family. The remittance feature is the core value proposition. Users want to see the exact exchange rate and fee before they send, track the transfer in real-time, and get confirmation when the recipient receives the money. I need a rails partner that provides real-time exchange rate quotes with locked pricing (so the rate shown to the user is the rate they get), processes the transfer within seconds of the user confirming, and delivers to the recipient's bank account or mobile wallet in their home country. The partner should support the top 10 remittance corridors from the US and provide webhook events for every transfer status change.",

  "I'm launching a remittance product for the US-to-El Salvador corridor. El Salvador is unique because it has adopted Bitcoin as legal tender alongside the US dollar, but most remittance recipients still prefer receiving dollars rather than Bitcoin. The traditional remittance process is expensive (4-6% fees) despite the short distance. We want to offer transfers where senders fund in dollars, the transfer settles through a cheap digital rail, and recipients receive dollars in their bank account or via cash pickup. The partner needs to have an El Salvador banking presence, the ability to deliver to local dollar-denominated accounts, and a cash pickup network covering the major cities and provincial towns. The partner should also be able to process transfers during weekends and holidays since remittance flows don't stop on weekends.",

  // total: 25 remittance_founder

  // ═══════════════════════════════════════════════════════════════
  // Persona 4: Enterprise Payments Lead (25)
  // Bank/enterprise treasury evaluating stablecoin settlement.
  // ═══════════════════════════════════════════════════════════════

  "I manage treasury operations for a Fortune 500 manufacturer. We operate in 40 countries and move about $500M annually in cross-border payments — paying suppliers, settling intercompany accounts, managing working capital across subsidiaries. Today this runs through our banking partners via SWIFT and correspondent banking. A typical cross-border payment to a supplier in China takes 2-3 business days and costs $25-40 in wire fees plus an invisible 0.5-1% in FX spread that our bank bakes into the exchange rate. Annually, we spend roughly $3M on cross-border payment costs. Our CFO wants us to evaluate whether digital settlement rails can reduce this. I need to understand if there's production-grade infrastructure that can handle enterprise payment volumes with the compliance and audit requirements our auditors demand. This isn't about crypto speculation — it's about moving our existing dollar-denominated payments through a faster, cheaper rail while maintaining the controls and visibility we have today.",

  "I lead payments strategy for a regional bank with $15B in assets. We're seeing our corporate clients increasingly ask about digital settlement options — they've read about stablecoins and instant settlement and want to know if we can offer it. We can't ignore this, but we also can't risk our reputation on experimental technology. I'm evaluating whether there's a white-label or partner model where we can offer our clients digital settlement rails without building the infrastructure ourselves. The ideal partner would operate in a regulated framework, handle the compliance and custody, and let us brand the service as our own. Our clients should interact with us as they always have — through their relationship manager and our online banking portal — while the backend settlement happens through more efficient rails. We need SOC-level security documentation, regulatory approvals in our operating states, and a partnership model that doesn't require us to hold digital assets on our balance sheet.",

  "I'm the treasury director at a large e-commerce company that pays thousands of marketplace sellers globally. Our seller payout process is a significant operational cost center — millions annually in cross-border fees and a dedicated treasury team that manages FX exposure across 30+ currency pairs. We've been watching the evolution of digital settlement infrastructure and believe there may be an opportunity to fundamentally restructure how we move money. I want to pilot a program where a portion of our seller payouts flow through a digital settlement rail as a proof of concept — comparing speed, cost, and reliability against our current banking rails. The pilot would need to run alongside our existing processes without disrupting seller payments. We need a partner that can handle a $10M monthly pilot volume, provide detailed transaction-level reporting for our comparison analysis, and operate with the security and compliance standards of a regulated financial institution.",

  "I head innovation for a global payment processor. We process billions in merchant settlements annually and are always looking for ways to improve settlement speed and reduce costs for our merchants. Our merchants currently receive settlements on a T+1 or T+2 basis depending on their processing agreement. Many of them, especially SMBs, would benefit from same-day or instant settlement. I'm exploring whether we can integrate a digital settlement rail as an optional accelerated settlement path for merchants who opt in. The integration would need to be seamless — when a merchant chooses instant settlement, our system routes their daily batch through the digital rail instead of the standard ACH file, and funds arrive in their bank account the same day. We need a partner that can handle high-volume batch processing, integrate with our existing settlement infrastructure via API, and provide the regulatory coverage for holding and moving funds on behalf of merchants across all 50 US states.",

  "I run payments for an international NGO that operates in 60+ countries, many of them with fragile banking systems. We move about $200M annually — paying local staff salaries, funding field office operations, transferring program funds to implementing partners in-country. The traditional banking process is a nightmare: a transfer to our South Sudan office can take 2 weeks, get stuck at an intermediary bank in Nairobi, and arrive with $50-100 in correspondent banking fees deducted from a $5,000 transfer. We need a more reliable, lower-cost way to move funds to our field operations that doesn't depend on fragile correspondent banking relationships. I'm evaluating whether digital settlement rails could give us direct, predictable fund transfers to our country offices without the intermediary bank chain. The solution needs to work in countries with limited banking infrastructure and be compliant with both US nonprofit regulations and local financial regulations in each operating country.",

  // 20 more enterprise...
  "I manage cross-border payments for a global supply chain finance platform. We connect large corporate buyers with their suppliers, offering suppliers early payment on their invoices in exchange for a small discount. The payments flow from the corporate buyer to us, and from us to thousands of suppliers across Asia, Europe, and Latin America. The current settlement process involves multiple banks and currency conversions, adding cost and delay. I want to move to a model where both the buyer payment and the supplier payout settle through a digital rail that's faster and cheaper than correspondent banking. The platform would hold a balance in a digital dollar, receive buyer payments into that balance, and disburse to suppliers in their local currency. The partner needs to handle the full flow — multi-currency collections, digital dollar holding, and local currency disbursements across 20+ countries. Enterprise-grade security, audit trail, and SOC compliance are required for our corporate clients.",

  "I'm evaluating blockchain settlement for a large insurance company that processes thousands of claims payouts monthly. When a policyholder files a claim and it's approved, the payout typically takes 3-5 business days via ACH or check. In catastrophe situations — hurricanes, wildfires — speed matters enormously. Policyholders need funds immediately to pay for hotels, repairs, and essentials. We want to offer instant claim payouts during catastrophes, where the moment a claim is approved, funds are in the policyholder's bank account within minutes. The solution needs to work at scale (thousands of payouts per day during a catastrophe event), integrate with our claims management system via API, and provide the security and compliance our regulators require. This is a pilot — we'd start with a specific catastrophe product and specific geography before expanding.",

  "I direct treasury for a university system with 12 campuses. We manage a $3B endowment and process thousands of payments — research grants to partner institutions, stipends to international students and researchers, payments to vendors and contractors. Our international payments are particularly inefficient: a research grant payment to a partner university in the UK takes 3-5 days and costs $30-50 in wire fees. We're a nonprofit and every dollar spent on banking fees is a dollar not going to research. I want to evaluate whether digital settlement can reduce our cross-border payment costs. The solution needs to be compatible with our existing ERP system, provide detailed audit trails for our annual financial audit, and meet the investment policy requirements of our board's finance committee.",

  "I lead payments infrastructure for a global money transfer company that processes $50B+ annually across 200+ countries. We operate our own network of agents and bank relationships, but we're always evaluating new settlement rails that can improve our cost structure. Digital dollar settlement is interesting to us as a potential alternative to the correspondent banking relationships we maintain in smaller corridors. In a corridor like US to Ghana, where correspondent banking relationships are thin and expensive, a digital settlement rail could meaningfully reduce our cost per transfer. We're looking to run a pilot in 3-5 corridors where we route a portion of our volume through a digital rail instead of our traditional banking partners. The pilot would need to demonstrate cost savings, equivalent or better reliability, and compliance with regulations in both the sending and receiving countries. We'd need API integration with our transfer processing system and detailed transaction reporting for our compliance team.",

  "I manage payments for a global charitable foundation that gives $500M+ annually in grants to organizations in 80+ countries. Our grant payments are unique because they often go to small local NGOs that don't have sophisticated banking relationships. A $50,000 grant to a women's cooperative in rural Uganda can get stuck at multiple correspondent banks, arrive with $200-300 in fees deducted, and take 2-3 weeks. We need a payment solution that can deliver funds directly to grantee bank accounts — or mobile money accounts where bank accounts don't exist — with predictable delivery times and transparent fee structures. The solution must be compliant with both US grant-making regulations and local financial regulations, provide detailed payment records for our audit requirements, and work across the full range of countries where we operate — from major economies to fragile states.",

  // 15 more enterprise...
  "I'm the CFO of a mid-size manufacturing company that imports raw materials from Asia and exports finished goods to Europe. Our cross-border payment volume is about $100M annually across 15 currencies. Every month our treasury team manually initiates wires, tracks exchange rates, reconciles what cleared, and manages FX exposure. It's a full-time job for two people. I want to automate this. I'm looking for a treasury management platform that connects our ERP to multiple settlement rails — traditional banking for familiar corridors and digital rails for corridors where they offer better speed and cost. The platform should handle the currency conversion, route each payment through the optimal rail based on cost and speed, and provide unified reporting. We're not looking to replace our banking relationships — we're looking to add digital rails as an additional tool in our treasury toolkit.",

  "I lead digital transformation for a commercial bank. We're building our 3-year technology roadmap and digital asset settlement is one of the areas the board has asked us to evaluate. The question is not whether to adopt — it's how. We need a partner that can help us pilot digital settlement with a small group of corporate clients, starting with a single corridor (US to Eurozone), with the option to expand. The pilot model should allow us to test the operational impact, compliance requirements, and client demand before committing to a broader rollout. We need a technology partner that provides the infrastructure, handles the regulatory complexity, and works alongside our existing core banking system — not a replacement for it.",

  "I manage cross-border operations for a remittance aggregator that connects money transfer operators to payment rails. We process about $2B annually across 100+ corridors, routing transfers through a network of banking partners, FX providers, and payout networks. Our margins are thin — we make money on the spread between wholesale and retail FX rates — and every basis point matters. Digital settlement rails are interesting because they could reduce our per-transfer cost by eliminating correspondent banking fees. I want to pilot routing 5% of our volume through a digital rail in 3 corridors and measure the cost difference against our traditional banking partners. The integration needs to support our existing transfer processing format, provide real-time settlement confirmation, and handle the compliance screening we already perform on every transfer.",

  "I'm the head of treasury for a large asset manager with $200B AUM. We make payments for fund expenses, management fees to service providers, and distributions to investors. Most of these are domestic, but we have growing international flows as our investor base diversifies. I'm interested in digital settlement for specific use cases: paying service providers in Europe and Asia (currently wire transfers, 2-3 days, $30-50 each) and processing investor redemptions to international bank accounts (where speed of payment affects client satisfaction). The solution must operate within our existing treasury controls — segregation of duties, dual approval for payments above certain thresholds, integration with our treasury management system. We're a regulated entity and our compliance requirements are non-negotiable.",

  "I direct payment strategy for a B2B payments network that connects corporate buyers with their suppliers. We process about $20B in payments annually, mostly through ACH and wire. Our corporate buyers want faster settlement and our suppliers want faster access to funds. We're exploring a 'fast lane' settlement option where approved invoices can be paid via a digital rail that settles in minutes instead of days. The fast lane would be optional — buyers choose which payments to accelerate — and we'd charge a small premium for the speed. The underlying rail needs to handle our volume, integrate with our invoice approval workflow, and provide the audit trail and compliance screening our bank partners require.",

  // total: 25 enterprise
];

import { writeFile, mkdir } from "node:fs/promises";
import { probeAds, countAds } from "../scraper/verseodin.js";

const CONCURRENCY = 8;
const OUT_DIR = "scraper-outputs-oms-loop2";

function sanitize(name: string): string {
  return name.replace(/[^a-z0-9]+/gi, "_").slice(0, 60).toLowerCase();
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  // Resume support: check which HTMLs already exist
  const existingFiles = new Set(
    (await import("node:fs/promises").then(fs => fs.readdir(OUT_DIR))).filter(f => f.endsWith(".html"))
  );

  let adsFound = 0;
  let skipped = 0;
  const advertisersSet = new Set<string>();
  const total = PROMPTS.length;

  for (let i = 0; i < total; i += CONCURRENCY) {
    const batch = PROMPTS.slice(i, i + CONCURRENCY);
    
    // Filter already-completed probes
    const pending = batch.map((prompt, j) => {
      const num = String(i + j + 1).padStart(3, "0");
      const fname = `${num}_${sanitize(prompt.slice(0, 70))}.html`;
      return { num, prompt, fname, alreadyDone: existingFiles.has(fname) };
    });

    const alreadyDone = pending.filter(p => p.alreadyDone).length;
    skipped += alreadyDone;
    if (alreadyDone > 0) {
      console.log(`[${String(i + 1).padStart(3)}-${String(Math.min(i + CONCURRENCY, total)).padStart(3)}] ${alreadyDone} already done (skipped)`);
    }

    const toRun = pending.filter(p => !p.alreadyDone);
    if (toRun.length === 0) continue;

    const batchStart = Date.now();

    const results = await Promise.all(
      toRun.map(async ({ num, prompt, fname }) => {
        try {
          const result = await probeAds(prompt, "US");
          const adCount = countAds(result.html);
          await writeFile(`${OUT_DIR}/${fname}`, result.html);
          return { num, prompt, adCount, htmlSize: result.html.length, ads: result.ads, ok: true };
        } catch (e) {
          return { num, prompt, adCount: 0, htmlSize: 0, ads: [], ok: false, err: e instanceof Error ? e.message : String(e) };
        }
      })
    );

    const elapsed = ((Date.now() - batchStart) / 1000).toFixed(0);
    for (const r of results) {
      if (r.ok && r.adCount > 0) {
        adsFound++;
        for (const ad of r.ads) {
          advertisersSet.add(ad.advertiser ?? "Unknown");
        }
      }
    }

    const success = results.filter(r => r.ok).length;
    const batchAds = results.filter(r => r.adCount > 0).length;
    const sizes = results.filter(r => r.ok).map(r => r.htmlSize);
    const avgSize = sizes.length ? (sizes.reduce((a, b) => a + b, 0) / sizes.length / 1024).toFixed(0) : "0";
    console.log(`[${String(i + 1).padStart(3)}-${String(Math.min(i + CONCURRENCY, total)).padStart(3)}] ${elapsed}s | ${success}/${batch.length} ok | ${batchAds} ads | avg ${avgSize}KB`);
    
    for (const r of results) {
      if (r.ok && r.adCount > 0) {
        for (const ad of r.ads) {
          console.log(`  🔴 [${r.num}] ${ad.advertiser}: "${ad.title}" — "${r.prompt.slice(0, 60)}..."`);
        }
      }
    }

    if (i + CONCURRENCY < total) {
      await new Promise((r) => setTimeout(r, 2000));
    }
  }

  console.log(`\n${"=".repeat(60)}`);
  console.log(`DONE. ${adsFound}/${total} prompts had ads.`);
  if (skipped > 0) console.log(`${skipped} prompts already existed and were skipped.`);
  console.log(`Unique advertisers: ${advertisersSet.size}`);
  if (advertisersSet.size > 0) {
    console.log(`Advertisers: ${[...advertisersSet].join(", ")}`);
  }
  console.log(`HTML files saved to ${OUT_DIR}/`);
}

main().catch(console.error);
